import { Poppins } from 'next/font/google'
// import './globals.css'
import CssBaseline from '@mui/material/CssBaseline'

const poppins = Poppins({ subsets: ['latin'], weight: ["300", "400", "500"] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <CssBaseline>
        <body className={poppins.className}>
          {children}
        </body>
      </CssBaseline>
    </html>
  )
}
